---
# These tasks install Apache web server

- name: Install Apache
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
   - apache2   
   - libapache2-mod-wsgi

- name: Enable Mod Proxy Apache modules
  command: a2enmod {{item}}
  with_items:
    - proxy
    - proxy_http

- name: Copy ACS Apache config
  copy: src=acs.conf dest=/etc/apache2/sites-available/acs.conf owner=root group=root mode=644

- name: Create dir for WSGI.py symlink
  file: state=directory recurse=yes path=/var/www/acs owner=root group=root

- name: Create symlink for WSGI.py
  file: src=/home/acs-user/acs/cvapp/wsgi.py dest=/var/www/acs/wsgi.py owner=root group=root state=link

- name: Create symlink for ACS apache conf
  file: src=/etc/apache2/sites-available/acs.conf dest=/etc/apache2/sites-enabled/acs.conf owner=root group=root state=link
  notify:
    - restart apache