---
# This playbook deploys a ACS to a Ubuntu server
- name: Set up ACS on server
  hosts: frontend_server
  user: ubuntu
  sudo: True
  vars:
    acs_github_url: https://raw.githubusercontent.com/altran/ACSSearch
  roles:
    - acs

    