---
# This playbook deploys a ACS to a Ubuntu server

- name: Set up Solr
  hosts: Solr_server
  sudo: True
  tags: solr
  roles:
    - solr
  vars:
    acs_search_github_url: https://raw.githubusercontent.com/altran/ACSSearch

- name: Set up Django
  hosts: ACS_Frontend
  sudo: True
  tags: django
  roles:
    - django
  vars:
    frontend_server_name: acs.altrancloud.com
    sso_url: https://sso.altran.se/

- name: Set up Apache
  hosts: ACS_Frontend
  sudo: True
  tags: apache
  roles:
    - apache
  vars:
    frontend_server_name: acs.altrancloud.com

- name: Set up Libreoffice for pdf/office export
  hosts: ACS_Frontend
  sudo: True
  tags: libreoffice
  roles:
    - libreoffice
