#Note problems with installing new libreoffice!
#- name: Install Libreoffice
#  apt: name=libreoffice

- name: Set apt-repository for Libreoffice 3.6.2
  apt_repository: repo='ppa:libreoffice/libreoffice-3-6' update_cache=yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'quantal'

- name: Install Libreoffice
  apt: name=libreoffice
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'quantal'


#Note problems with installing/finding libreoffice 3.6.2
#The following code snippets will install libreoffice on an old Ubuntu Quantal
#sudo add-apt-repository
# sudo apt-get update
# sudo apt-get install libreoffice
#when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'quantal'


- name: Cron for restarting Libreoffice
  cron: name="Libreoffice restart" minute="0" hour="3" job="soffice --invisible --headless '--accept=socket,host=localhost,port=2002;urp;'" user=acs-user
  #sudo_user: acs-user
  

- name: Configure Libreoffice
  shell: soffice --invisible --headless "--accept=socket,host=localhost,port=2002;urp;"
  sudo_user: acs-user
