- name: Cron for restarting Libreoffice
  cron: name="Libreoffice restart" minute="0" hour="3" job="libreoffice --invisible --headless '--accept=socket,host=localhost,port=2002;urp;' &" user=acs-user

- name: Install Libreoffice
  apt: name=libreoffice-common state=present

- name: Configure Libreoffice
  shell: libreoffice --invisible --headless "--accept=socket,host=localhost,port=2002;urp; &"
  sudo_user: acs-user
