# Jetty creates its own user
#- name: create "Solr" user solr
#  user: name=solr
#  sudo: True

#- name: Fetch Solr distro
#  get_url: url={{solr_download_url}} dest=/tmp/{{solr_ident}}.tgz
#  register: solr_download

#- name: Pack out Solr
#  sudo: True
#  sudo_user: solr
#  command: tar -xf /tmp/{{solr_ident}}.tgz -C /home/solr/
#  when: solr_download.changed


- name: Install Solr and Java dependencies
  sudo: True
  apt: name={{ item }} state=present
  with_items:
   - openjdk-7-jdk 
   - openjdk-7-doc 
   - openjdk-7-source
   - solr-jetty

- name: Copy Solr password file
  copy: src=solr-password dest=/home/acs-user/password owner=acs-user group=acs-user
  sudo: True

- name: Configure Jetty to be startable
  lineinfile: dest=/etc/default/jetty regexp="NO_START=" line="NO_START=0"
  sudo: True
  register: JettyRestarted

- name: Start up jetty/Solr
  sudo: True
  service: name=jetty state=restarted

- name: Restart Apache
  sudo: True
  service: name=apache2 state=restarted
