
- name: update apt
  apt: update_cache=yes cache_valid_time=3600
  sudo: true

- name: Install Java and other dependencies
  sudo: True
  apt: name={{ item }} state=present
  with_items:
   - openjdk-7-jdk 
   - openjdk-7-doc 
   - openjdk-7-source