---
# These tasks install Apache web server

- name: Install Apache
  sudo: True
  apt: name={{ item }} state=present
  with_items:
   - apache2
   - git
   - lynx
   
- name: http service state
  service: name=apache2 state=started enabled=yes