- name: create "Solr" user solr
  user: name=solr
  tags: solr

- name: Copy Solr password file
  copy: src=solr-password dest=/home/acs-user/password owner=acs-user
  tags: solr

- name: Create Solr acs-search directory
  file: state=directory recurse=yes path=/home/solr/acs-search owner=solr group=solr
  tags: solr

# ACS must be placed in /opt/... to be run as a demon
#- name: Copy Solr demon script
#  get_url: url={{acs_github_url}}/master/init.d_AcsSearch dest=/etc/init.d/acs-search mode=0755
#  tags: solr

- name: Copy Solr startup script
  get_url: url={{acs_github_url}}/master/{{item}} dest=/home/solr/acs-search/{{item}} mode=0744
  with_items:
    - start-service.sh
    - stop-service.sh
  sudo_user: solr
  tags: solr

- name: Start up Solr
  command: /home/solr/acs-search/start-service.sh >> somelog.txt chdir=/home/solr/acs-search
  sudo_user: solr
  tags: solr