---
# These tasks install Django Web application framework
- name: Install Django dependencies
  apt: name={{ item }} state=present
  with_items:
   - git
   - python-pip
   - python-lxml
   - libxml2-dev 
   - libxslt-dev
   - python-imaging # May be a requirement
   - libpq-dev
   - python-dev

- name: Install Python dependencies with pip
  pip: name={{item}}
  with_items:
   - Django#==1.6.2
   - django-admin-bootstrapped#==1.6.4
   - django-haystack
   - pysolr#==3.2.0
   - appy#==0.8.
   - django-webodt
   - psycopg2

# If still problems with lxml: pip install --upgrade lxml
- name: Upgrade Python Lxml
  pip: name=lxml
    extra_args='--upgrade'

- name: create "Django" user acs-user
  user: name=acs-user group=www-data shell="/bin/bash"

  # This script will not always run and may require to be run manually
- name: Git clone Awesome-Competence-System into acs-user
  action: git repo=https://github.com/altran/Awesome-Competence-System.git dest=/home/acs-user/acs
  sudo_user: acs-user

- name: Configure Django localsettings.py
  template: src=localsettings.py.jinja dest=/home/acs-user/acs/cvapp/localsettings.py backup=yes owner=acs-user group=www-data mode=0644

#- name: Install django-webodt
#easy_install: name:django-webodt

- name: Create www/static
  file: state=directory recurse=yes path=/var/www/static


- name: Create var/www/media/ photos and templates folders
  file: state=directory recurse=yes path={{item}} owner=www-data group=www-data
  with_items:
    - /var/www/media/photos
    - /var/www/media/templates

- name: Create Django Log directory
  file: state=directory recurse=yes path=/var/log/django owner=www-data group=www-data

- name: Touch django log file for correct rights
  file: state=touch path=/var/log/django/logfile owner=www-data group=www-data

- name: Python Collect static files into /var/www/static
  shell: echo "yes" | python /home/acs-user/acs/cvapp/manage.py collectstatic

- name: Copy Solr password file
  template: src=solr-password.jinja dest=/home/acs-user/password backup=yes owner=acs-user group=www-data mode=644

- name: Index ACS site in Solr
  shell: echo "y" | python /home/acs-user/acs/cvapp/manage.py rebuild_index

- name: Set file ownership of all acs correctly
  file: state=file path={{item}} owner=acs-user group=www-data mode=644
  with_items:
    - /home/acs-user/acs/cvapp/localsettings.pyc
    - /home/acs-user/acs/cvapp/settings.pyc
